
export const	getDynamicList   =    '/api/v1/dynamic/user/list' //用户动态列表
export const	getUserDetail    =    '/api/v1/user/detail' //用户信息详情
export const	getDetail        =    '/api/v1/dynamic/detail' //详情
export const	getPhotoDetail   =    '/api/v1/dynamic/photo/detail' //详情
export const	getPhotoStatus   =    '/api/v2/dynamic/region/photo/status' //获取照片关注状态
export const	getGoods         =    '/api/v1/good/list' //赞列表
export const	commentList      =    '/api/v1/comment/list' //评论列表
export const	phoneLogin       =    '/api/v1/user/login' //手机登陆
export const	getCode          =    '/api/v1/user/send/sms' //获取验证码
export const	otherLogin       =    '/api/v1/user/register' //第三方登陆
export const	collection       =    '/api/v2/dynamic/collection' //收藏
export const	collectionCancle =    '/api/v2/dynamic/collection/cancle' //取消收藏
export const	commentAdd       =    '/api/v1/comment/add' //评论
export const	goodAdd          =    '/api/v1/good/add' //点赞
export const	cancleAdd        =    '/api/v1/good/cancle' //取消赞
export const	getweiboToken    =    '/api/v1/weibo/accesstoken' //获取微博token
export const	getweixinToken   =    '/api/v1/weixin/accesstoken' //获取微信token
export const	getweixinUserinfo=    '/api/v1/weixin/userinfo' //获取微信token
export const    readRank         =    '/api/v2/dynamic/read/rank' //阅读榜
export const    fansList         =    '/api/v1/friend/fans/list' //用户粉丝列表
export const    followFansList   =    '/api/v1/friend/follow/list' //我关注的用户列表
export const    dynamicPhotoCount=    '/api/v1/dynamic/dynamicPhotoCount' //用户图
export const    dynamicList      =    '/api/v2/dynamic/map/user/list' //用户图片
export const	score            =    '/api/v2/dynamic/score' //用户评分
export const	cityList         =    '/api/v2/dynamic/city/list' //用户城市照片分类
export const	countryList      =    '/api/v2/dynamic/country/list' //用户国家照片分类
export const	scoreList        =    '/api/v1/user/rank/score' //用户评分榜
export const	photoLocation    =    '/api/v2/dynamic/photo/location' //获得国家、市照片
export const	photoLocationMap =    '/api/v2/dynamic/map/photo/location' //获得国家、市照片地图模式
export const	region           =    '/api/v1/user/follow/region' //关注区域
export const	cancleRegion     =    '/api/v1/user/follow/region/cancle' //取消关注区域
export const	addFriend        =    '/api/v1/friend/add' //添加朋友
export const	cancleFriend     =    '/api/v1/friend/cancle' //取消朋友
export const    dynamicMpa       =    '/api/v2/dynamic/map/dynamic/list' //动态详情，地图模式
export const    followList       =    '/api/v2/dynamic/follow/list' //首页-关注列表
export const    followListMap    =    '/api/v2/dynamic/map/follow/list' //首页-关注列表地图模式
export const    findList         =    '/api/v2/dynamic/find/listv2' //首页-发现列表
export const    findListMap      =    '/api/v1/dynamic/map/polymeric/list' //首页-发现列表地图
export const    hotList          =    '/api/v2/dynamic/hot/list' //首页-热门列表
export const    hotListMap       =    '/api/v1/dynamic/map/hot/polymeric/list' //首页-热门列表地图模式
export const    messageCenter    =    '/api/v1/user/message/center' //消息中心
export const    collectionDynamic=    '/api/v2/dynamic/collection/list' //收藏动态列表
export const    regionList       =    '/api/v1/user/follow/region/list' //用户关注地址列表
export const    feedback         =    '/api/v1/user/feedback' //用户反馈
export const    searchUser         =    '/api/v1/user/search' //搜索用户
export const    searchFriend         =    '/api/v1/user/search/friend' //搜索好友
export const    dynamicReport         =    '/api/v1/dynamic/report' //动态举报
